### ISSUE TITLE
Error with 0.4.6 in extractor.js

### ISSUE THREAD

**Issue by WRidder** [jonathanepollack/gulp-minify-css#71] opened 2015-02-27 15:23 UTC
Using 0.4.6 I get the following error:

    /home/travis/build/WRidder/react-spa/node_modules/gulp-minify-css/node_modules/clean-css/lib/properties/extractor.js:47
    return name.replace(/^\-\w+\-/, '').match(/([a-z]+)/)[0];
                                                       ^
    TypeError: Cannot read property '0' of null

This error is not present in 0.4.5. Did not investigate further yet what may cause the problem, maybe anyone has a clue right away?

**Comment by shinnn** [comment] 2015-02-27 15:28
Maybe duplicate of https://github.com/jakubpawlowicz/clean-css/issues/469

**Comment by jakubpawlowicz** [comment] 2015-02-27 20:05
I've just released 3.1.1 with the fix.

Please note you should not use `"clean-css": "^3.0.4"` in package.json, but rather something like `"clean-css": "~3.0.4"` and bump your minor version when upgrading dependencies. Otherwise people will suddenly start running into issues without a good reason - see http://semver.org/

**Closed** 2015-02-27 20:34 UTC

**Comment by shinnn** [comment] 2015-02-27 21:12
@jakubpawlowicz 

If you really think so, open issues on many other projects using `^` operators in their dependencies.

This is not a semver-related issue but just a clean-css-related issue.
