### ISSUE TITLE
Error when using "safari 5" in autoprefixer browser list vs. "safari 6"

### ISSUE THREAD

**Issue by dustinhansen** [jonathanepollack/gulp-minify-css#72] opened 2015-03-02 03:42 UTC
I'm running into an issue when trying to utilize gulp-sourcemaps, gulp-autoprefixer and gulp-minify-css together. Here's my gulp task:

var gulp = require('gulp'),
$ = require('gulp-load-plugins')();

gulp.task('test', function()
{
return gulp.src('app/assets/scss/main.scss')
.pipe($.sourcemaps.init())
.pipe($.sass({
includePaths: ['node_modules/bootstrap-sass/assets/stylesheets/'],
outputStyle: 'expanded'
}))
.pipe($.autoprefixer({
browsers: ['last 2 versions', 'safari 5', 'ie 8', 'ie 9', 'opera 12.1', 'ios 6', 'android 4']
}))
.pipe($.minifyCss())
.pipe($.sourcemaps.write('./maps', {
includeContent: false,
sourceRoot: '.'
}))
.pipe(gulp.dest('dist/assets/css'));
});

This is the error I get:

TypeError: Cannot read property '0' of null
at findNameRoot (/var/www/node_modules/gulp-minify-css/node_modules/clean-css/lib/properties/extractor.js:47:56)
at extract (/var/www/node_modules/gulp-minify-css/node_modules/clean-css/lib/properties/extractor.js:17:22)
at AdvancedOptimizer.restructure (/var/www/node_modules/gulp-minify-css/node_modules/clean-css/lib/selectors/optimizers/advanced.js:598:22)
at _optimize (/var/www/node_modules/gulp-minify-css/node_modules/clean-css/lib/selectors/optimizers/advanced.js:722:12)
at AdvancedOptimizer.optimize (/var/www/node_modules/gulp-minify-css/node_modules/clean-css/lib/selectors/optimizers/advanced.js:734:3)
at SelectorsOptimizer.process (/var/www/node_modules/gulp-minify-css/node_modules/clean-css/lib/selectors/optimizer.js:15:55)
at /var/www/node_modules/gulp-minify-css/node_modules/clean-css/lib/clean.js:174:31
at run (/var/www/node_modules/gulp-minify-css/node_modules/clean-css/lib/clean.js:153:7)
at minify (/var/www/node_modules/gulp-minify-css/node_modules/clean-css/lib/clean.js:165:3)
at whenSourceMapReady (/var/www/node_modules/gulp-minify-css/node_modules/clean-css/lib/clean.js:90:7)

If I change "safari 5" to "safari 6" in the gulp-autoprefixer browsers array, the task runs fine. Any ideas?

**Comment by shinnn** [comment] 2015-03-02 05:06
Which version of gulp-minify-css are you using?

**Comment by shinnn** [comment] 2015-03-02 06:43
I found the cause. It's just a duplicate of #71.

Re-installing gulp-minify-css fixes this problem.

**Closed by shinnn** 2015-03-02 06:43 UTC
